trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: Build and Test
    jobs:
      - job: Build
        steps:
          - task: UseDotNet@2
            displayName: Install .NET 10
            inputs:
              packageType: sdk
              version: '10.x'

          - script: dotnet restore
            displayName: Restore

          - script: dotnet build --no-restore --configuration Release
            displayName: Build

          - script: dotnet test --no-build --configuration Release
            displayName: Test

  - stage: Docker
    displayName: Build and Push Docker Image
    dependsOn: AzureTest
    condition: succeeded()
    jobs:
      - job: Docker
        steps:
          - task: AzureCLI@2
            displayName: Build and Push Docker Image
            inputs:
              azureSubscription: 'CertifyAB-Azure'
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                IMAGE="acrcertifyabemm.azurecr.io/certifyab:$(Build.BuildId)"

                echo "Building image:"
                echo "$IMAGE"

                docker build -t "$IMAGE" .

                if [ "$(Build.SourceBranch)" = "refs/heads/main" ]; then

                  echo "Main branch detected."
                  echo "Pushing image to ACR..."

                  az acr login --name acrcertifyabemm
                  docker push "$IMAGE"

                else

                  echo "PR build detected."
                  echo "Image will NOT be pushed to ACR."

                fi

  - stage: Infrastructure
    displayName: Deploy Infrastructure
    dependsOn: Docker
    condition: |
      and(
        succeeded(),
        eq(variables['Build.SourceBranch'], 'refs/heads/main')
      )
    jobs:
      - job: Deploy
        steps:
          - task: AzureCLI@2
            displayName: Deploy Bicep
            inputs:
              azureSubscription: 'CertifyAB-Azure'
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                IMAGE="acrcertifyabemm.azurecr.io/certifyab:$(Build.BuildId)"

                echo "Deploying image:"
                echo "$IMAGE"

                az deployment group create \
                  --resource-group "RG-Emma-Spitz-a59389-DotNetCloudDeveloper-VT-Mars-Goteborg" \
                  --template-file Infra/main.bicep \
                  --parameters \
                    Infra/main.prod.bicepparam \
                    containerImage="$IMAGE" \
                    apiKey="$API_KEY"
            env:
              API_KEY: $(API_KEY)
